# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WoodFish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WoodFish

pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'Masonry'
pod 'MarqueeLabel'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
